name: Flutter CI/CD

on:
  push:
    branches:
      - "master"

jobs:
  # CI
  build_android:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel : stable

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: key.jks
          encodedString: ${{ secrets.SIGNING_KEY }}

      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.KEY_STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ALIAS }}" >> android/key.properties

      # - name: Format files
      #   run: flutter format --set-exit-if-changed .

      # - name: Analyze files
      #   run: flutter analyze .

      # - name: Run the tests
      #   run: flutter test

      - name: Build android app bundle
        id: sign_app
        run:  flutter build appbundle --release

      - uses: actions/upload-artifact@v2
        with:
          name: Upload signed app bundle
          path: build/app/outputs/bundle/release/app-release.aab

  # CD
  deploy_android:
    runs-on: ubuntu-latest
    needs: [build_android]
    steps:

      - name: Retrieve artifacts from Build stage
        uses: actions/download-artifact@v2
        with:
          name: Upload signed app bundle
          path: ./aab

      - name: Uploading to Google Play store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: io.madhank93.todo_app_with_flutter_and_firebase
          releaseFiles: ./aab/app-release.aab
          track: production
